Deploy new Post Auth function from CodePipeline
BIBSYSDEV/nva-cognito-post-authentication-trigger pull request #4
Opened 2020-08-26 11:38 UTC by janbj

Give permission to read secret from Secret Manager
Use SecretReader from nva-commons to read Secret
Updated templates

2020-08-26 12:52 UTC, brinxmat approved these changes

2020-08-26 14:42 UTC, axthosarouris commented on cognito-post-authentication/src/main/java/no/unit/nva/cognito/PostAuthenticationHandler.java
> +        Event event = JsonUtils.objectMapper.convertValue(input, Event.class);
Just a comment here to remember why this is necessary.

2020-08-26 14:45 UTC, axthosarouris requested changes

2020-08-26 14:45 UTC, axthosarouris commented on cognito-post-authentication/src/test/java/no/unit/nva/cognito/model/EventTest.java
> +    public static final String SAMPLE_EVENT_JSON = "src/test/resources/sample_event.json";
Use IoUtils.stringFromResources and you do not need to set such a path. This path is going to fail if someone runs the code on Windows.

2020-08-27 06:00 UTC, axthosarouris approved these changes

2020-08-27 06:01 UTC, merged